### ISSUE TITLE
Connect with k8s clusters that based their auth on OIDC

### ISSUE THREAD

**Issue by jjuarez** [Trois-Six/k8s-diagrams#4]
First of all, thanks for this promising project; So, I'm just trying to connect with one of my kubernetes clusters and I had this error:

```text
2021/04/27 22:39:25 creating kubernetes client: no Auth Provider found for name "oidc"
```

The cluster is an IKS on IBMCloud and the auth of the kubeconfig is based on some tokens and the IBMCloud auth system

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /Users/foo/.bluemix/plugins/container-service/clusters/apis-dev-bq1q5dvd0s7sa54sdtlg/ca-aaa00-apis-dev.pem
    server: https://c2.us-south.containers.cloud.ibm.com:24441
  name: apis-dev/bq1q5dvd0s7sa54sdtlg
contexts:
- context:
    cluster: apis-dev/bq1q5dvd0s7sa54sdtlg
    namespace: default
    user: foo.bar@ibm.com/[REDACTED]/iam.cloud.ibm.com-identity
  name: apis-dev/bq1q5dvd0s7sa54sdtlg
current-context: apis-dev/bq1q5dvd0s7sa54sdtlg
kind: Config
preferences: {}
users:
- name: foo.bar@ibm.com/[REDACTED]/iam.cloud.ibm.com-identity
  user:
    auth-provider:
      config:
        client-id: kube
        client-secret: kube
        id-token: [REDACTED]
        idp-issuer-url: https://iam.cloud.ibm.com/identity
        refresh-token: [REDACTED]
      name: oidc
```

Unfortunately, I'm not able to make a pull request to solve the issue because golang is not my speciallity, but I saw [this issue](https://github.com/kubernetes/client-go/issues/345) in the k8s go-client project, it could be helpful...I hope.

thanks!
